# Generated by Django 5.2.7 on 2025-11-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS events_event (
                id BIGSERIAL PRIMARY KEY,
                title VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                date DATE,
                time TIME,
                location VARCHAR(255) NOT NULL,
                formatted_address VARCHAR(255) NOT NULL DEFAULT '',
                latitude DOUBLE PRECISION,
                longitude DOUBLE PRECISION,
                banner VARCHAR(100),
                video VARCHAR(100),
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                organizer_id BIGINT REFERENCES accounts_organizerprofile(id) ON DELETE CASCADE
            );
            
            CREATE TABLE IF NOT EXISTS events_eventtimeslot (
                id BIGSERIAL PRIMARY KEY,
                date DATE NOT NULL,
                start_time TIME NOT NULL,
                end_time TIME NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                event_id BIGINT NOT NULL REFERENCES events_event(id) ON DELETE CASCADE
            );
            
            CREATE INDEX IF NOT EXISTS events_eventtimeslot_event_id_idx ON events_eventtimeslot(event_id);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS events_eventtimeslot CASCADE;
            DROP TABLE IF EXISTS events_event CASCADE;
            """,
            state_operations=[
                migrations.CreateModel(
                    name="Event",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("title", models.CharField(max_length=200)),
                        ("description", models.TextField(blank=True)),
                        ("date", models.DateField(blank=True, null=True)),
                        ("time", models.TimeField(blank=True, null=True)),
                        ("location", models.CharField(max_length=255)),
                        ("formatted_address", models.CharField(blank=True, max_length=255)),
                        ("latitude", models.FloatField(blank=True, null=True)),
                        ("longitude", models.FloatField(blank=True, null=True)),
                        ("banner", models.ImageField(blank=True, null=True, upload_to="banners/")),
                        ("video", models.FileField(blank=True, null=True, upload_to="event_videos/")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("organizer", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="creates", to="accounts.organizerprofile")),
                    ],
                ),
                migrations.CreateModel(
                    name="EventTimeSlot",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("date", models.DateField()),
                        ("start_time", models.TimeField()),
                        ("end_time", models.TimeField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="time_slots", to="events.event")),
                    ],
                    options={"ordering": ["date", "start_time"]},
                ),
            ],
        ),
    ]