# Generated by Django 5.2.7 on 2025-10-20 16:40

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        # Depend on whatever migration creates OrganizerProfile.
        # If your accounts app starts at 0001 with OrganizerProfile, keep this:
        ("accounts", "0001_initial"),
    ]

    operations = [
        # Keep state in sync so Django "knows" the field exists.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="event",
                    name="organizer",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creates",
                        to="accounts.organizerprofile",
                    ),
                ),
            ],
            database_operations=[
                # 1) Add column only if it doesn't exist
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_name = 'events_event'
                          AND column_name = 'organizer_id'
                      ) THEN
                        ALTER TABLE events_event
                          ADD COLUMN organizer_id BIGINT NULL;
                      END IF;
                    END$$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # 2) Add FK only if it doesn't already exist
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint c
                        JOIN pg_class t ON c.conrelid = t.oid
                        JOIN pg_class r ON c.confrelid = r.oid
                        WHERE c.contype = 'f'
                          AND t.relname = 'events_event'
                          AND r.relname = 'accounts_organizerprofile'
                      ) THEN
                        ALTER TABLE events_event
                          ADD CONSTRAINT events_event_organizer_id_fk
                          FOREIGN KEY (organizer_id)
                          REFERENCES accounts_organizerprofile(id)
                          DEFERRABLE INITIALLY DEFERRED;
                      END IF;
                    END$$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # 3) Clean up old table if someone still has it locally
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS events_ticket CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
