# Generated by Django 5.2.7 on 2025-11-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_formatted_address_event_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
