# Generated by Django 5.2.7 on 2025-12-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_cancelled_at_event_is_cancelled"),
        ("events", "0003_eventnotificationsubscription"),
    ]

    operations = []
