# Generated by Django 5.2.7 on 2025-11-21 20:11

import django.db.models.deletion  # noqa: F401  (kept for historical reasons)
from django.db import migrations, models  # noqa: F401


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    # NOTE:
    # This migration originally added the `ticket_info` field to Order,
    # but that field is now created in an earlier migration
    # (0001_squashed_0004_alter_billinginfo_full_name / 0001_initial),
    # so re-adding it causes a DuplicateColumn error.
    #
    # We leave this migration file in place (so Django's migration graph is happy)
    # but with no operations.
    operations = []
