# Generated by Django 5.2.7 on 2025-10-31 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_billing_info_delete_billinginfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="billing_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billingfor",
                to="orders.billinginfo",
            ),
        ),
    ]
