# Generated by Django 5.2.7 on 2025-11-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_billinginfo_order_billing_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billinginfo",
            name="full_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
