# Generated by Django 5.2.7 on 2025-12-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        ("orders", "0005_order_quantity"),
    ]

    operations = []
