# Generated by Django 5.2.7 on 2025-12-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_email"),
        ("orders", "0006_merge_0002_initial_0005_order_quantity"),
    ]

    operations = []
