# Generated by Django 5.2.7 on 2025-12-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_refunded",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("refund_processing", "Refund Processing"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
