# Generated by Django 5.2.7 on 2025-12-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_merge_20251208_0059"),
        ("orders", "0007_order_amount_refunded_alter_order_status"),
    ]

    operations = []
