"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from config.secrets import get_secret


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Load env var
ENVIRONMENT = os.getenv("ENVIRONMENT", "local")

if ENVIRONMENT == "local":
    load_dotenv()

# # --- Media files ---

if ENVIRONMENT in ["production", "development"]:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": os.getenv("AWS_MEDIA_BUCKET_NAME"),
                "querystring_auth": True,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://{os.getenv('AWS_MEDIA_BUCKET_NAME')}.s3.amazonaws.com/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {"location": BASE_DIR / "media"},
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if ENVIRONMENT in ["production", "development"]:
    DJANGO_SECRET_KEY_NAME = os.getenv("DJANGO_SECRET_KEY_NAME")
    DB_SECRETS_NAME = os.getenv("DB_SECRETS_NAME")

    SECRET_KEY = get_secret(DJANGO_SECRET_KEY_NAME)["SECRET_KEY"]
    secrets = get_secret(DB_SECRETS_NAME)
else:
    SECRET_KEY = "local-secret"
    secrets = {
        "username": os.getenv("POSTGRES_USER", "postgres"),
        "password": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "host": os.getenv("POSTGRES_HOST", "localhost"),
        "port": os.getenv("POSTGRES_PORT", "5432"),
        "dbInstanceIdentifier": os.getenv("POSTGRES_DB", "simpletix-local-db"),
        "dbname": os.getenv("POSTGRES_DB_NAME", "simpletix"),
    }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": secrets["dbname"],
        "USER": secrets["username"],
        "PASSWORD": secrets["password"],
        "HOST": secrets["host"],
        "PORT": secrets["port"],
    }
}

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == "production":
    DEBUG = False
elif ENVIRONMENT == "development":
    DEBUG = True
else:
    DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "simpletix-dev.eba-fygzzpfp.us-east-1.elasticbeanstalk.com",
    "simpletix-prod.eba-fygzzpfp.us-east-1.elasticbeanstalk.com",
    "172.31.0.0/16",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "events",
    "simpletix",
    "ebhealthcheck.apps.EBHealthCheckConfig",
    "accounts.apps.AccountsConfig",
    "tickets",
    "storages",
    "orders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.multi_session_middleware.MultiSessionMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.session_flags",
                "config.context_processors.algolia_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/var/www/simpletix/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Login ---

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
# Where to send users if ?next isn't provided.
LOGOUT_REDIRECT_URL = "/accounts/start/"


# --- Algoila Settings ---

if os.getenv("CI", "false").lower() == "true":
    # Disable Algolia entirely in CI builds
    ALGOLIA = {
        "APPLICATION_ID": "",
        "API_KEY": "",
        "SEARCH_KEY": "",
        "INDEX_PREFIX": "ci-skip",
    }
    ALGOLIA_ENABLED = False
elif ENVIRONMENT in ["production", "development"]:
    secrets = get_secret(os.getenv("ALGOLIA_SECRETS_NAME"))
    ALGOLIA = {
        "APPLICATION_ID": secrets.get("ALGOLIA_APP_ID", ""),
        "API_KEY": secrets.get("ALGOLIA_API_KEY", ""),
        "SEARCH_KEY": secrets.get("ALGOLIA_SEARCH_KEY", ""),
        "INDEX_PREFIX": secrets.get("ALGOLIA_INDEX_PREFIX", "simpletix"),
    }
    ALGOLIA_ENABLED = True
else:
    ALGOLIA = {
        "APPLICATION_ID": os.getenv("ALGOLIA_APP_ID", ""),
        "API_KEY": os.getenv("ALGOLIA_API_KEY", ""),
        "SEARCH_KEY": os.getenv("ALGOLIA_SEARCH_KEY", ""),
        "INDEX_PREFIX": os.getenv("ALGOLIA_INDEX_PREFIX", "simpletix"),
    }
    ALGOLIA_ENABLED = os.getenv("ALGOLIA_ENABLED", True)


# --- GOOGLE MAPS SETTINGS ---

if os.getenv("CI", "false").lower() == "true":
    GOOGLE_MAPS_API_KEY = ""
elif ENVIRONMENT in ["production", "development"]:
    google_secrets_name = os.getenv("GOOGLE_MAPS_SECRETS_NAME")
    google_secrets = get_secret(google_secrets_name)
    GOOGLE_MAPS_API_KEY = google_secrets.get("GOOGLE_MAPS_API_KEY", "")
else:
    GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")


# --- Email / SMTP configuration ---

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

if ENVIRONMENT in ["production", "development"]:
    email_secrets = get_secret(os.getenv("EMAIL_SECRETS_NAME"))
    EMAIL_HOST_USER = email_secrets.get("SMTP_USER", "")
    EMAIL_HOST_PASSWORD = email_secrets.get("SMTP_PASSWORD", "")
else:
    # Local / CI: read from .env or shell env vars
    EMAIL_HOST_USER = os.getenv("SMTP_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("SMTP_PASSWORD", "")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@example.com"


# STRIPE CONFIGURATION
if ENVIRONMENT in ["production", "development"]:
    secrets = get_secret(os.getenv("STRIPE_SECRETS_NAME"))
    STRIPE = {
        "STRIPE_PUBLISHABLE_KEY": secrets.get("STRIPE_PUBLISHABLE_KEY", ""),
        "STRIPE_SECRET_KEY": secrets.get("STRIPE_SECRET_KEY", ""),
        "STRIPE_WEBHOOK_SECRET": secrets.get("STRIPE_WEBHOOK_SECRET", ""),
    }
else:
    STRIPE = {
        "STRIPE_PUBLISHABLE_KEY": os.getenv("STRIPE_PUBLISHABLE_KEY", ""),
        "STRIPE_SECRET_KEY": os.getenv("STRIPE_SECRET_KEY", ""),
        "STRIPE_WEBHOOK_SECRET": os.getenv("STRIPE_WEBHOOK_SECRET", ""),
    }

# --- GOOGLE MAPS SETTINGS ---

if os.getenv("CI", "false").lower() == "true":
    GOOGLE_MAPS_API_KEY = ""
elif ENVIRONMENT in ["production", "development"]:
    google_secrets_name = os.getenv("GOOGLE_MAPS_SECRETS_NAME")
    google_secrets = get_secret(google_secrets_name)
    GOOGLE_MAPS_API_KEY = google_secrets.get("GOOGLE_MAPS_API_KEY", "")
else:
    GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")
