"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from config.secrets import get_secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load Env vars + get Database Secrets
load_dotenv()
ENVIRONMENT = os.getenv("ENVIRONMENT", "local")

if ENVIRONMENT in ["production", "development"]:
    DJANGO_SECRET_KEY_NAME = os.getenv("DJANGO_SECRET_KEY_NAME")
    DB_SECRETS_NAME = os.getenv("DB_SECRETS_NAME")

    SECRET_KEY = get_secret(DJANGO_SECRET_KEY_NAME)["SECRET_KEY"]
    secrets = get_secret(DB_SECRETS_NAME)
else:
    SECRET_KEY = "local-secret"
    secrets = {
        "username": os.getenv("POSTGRES_USER", "postgres"),
        "password": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "host": os.getenv("POSTGRES_HOST", "localhost"),
        "port": os.getenv("POSTGRES_PORT", "5432"),
        "dbInstanceIdentifier": os.getenv("POSTGRES_DB", "simpletix-local-db"),
        "dbname": os.getenv("POSTGRES_DB_NAME", "simpletix"),
    }

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": secrets["dbname"],
        "USER": secrets["username"],
        "PASSWORD": secrets["password"],
        "HOST": secrets["host"],
        "PORT": secrets["port"],
    }
}

# Security / Debug
if ENVIRONMENT == "production":
    DEBUG = False
elif ENVIRONMENT == "development":
    DEBUG = True
else:
    DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "simpletix-dev.eba-fygzzpfp.us-east-1.elasticbeanstalk.com",
    ("simpletix-prod." "eba-fygzzpfp.us-east-1.elasticbeanstalk.com"),
    "172.31.0.0/16",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "events",
    "simpletix",
    "home",
    "ebhealthcheck.apps.EBHealthCheckConfig",
    "accounts.apps.AccountsConfig",
    "tickets",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.session_flags",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = "/static/"
STATIC_ROOT = "/var/www/simpletix/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication redirects
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"  # where to send users if ?next isn’t provided
LOGOUT_REDIRECT_URL = "/accounts/start/"  # After logout, go to Get Started

# Algolia Search
ALGOLIA = {
    "APPLICATION_ID": os.getenv(
        "ALGOLIA_APP_ID",
        "dummy",
    ),
    "API_KEY": os.getenv(
        "ALGOLIA_API_KEY",
        "dummy",
    ),
    "INDEX_PREFIX": "simpletix_",  # optional
}
