# Generated by Django 5.2.7 on 2025-11-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    # NOTE:
    # The fields `issued_at`, `order_id`, `qr_code`, and `status`
    # are already created in 0001_initial.
    # This migration is now intentionally a no-op to avoid duplicate column errors.
    operations = []
