# Generated by Django 5.2.7 on 2025-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="order_id",
            field=models.CharField(
                blank=True,
                help_text="Group tickets that belong to the same checkout/payment.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="qr_code",
            field=models.CharField(
                blank=True,
                help_text="QR payload or unique ticket code.",
                max_length=160,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="PENDING / ISSUED / USED. Left null for legacy tickets.",
                max_length=20,
                null=True,
            ),
        ),
    ]
