# Generated by Django 5.2.7 on 2025-11-16 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_issued_at_ticket_order_id_ticket_qr_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketinfo",
            name="availability",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="ticketinfo",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0.5)],
            ),
        ),
    ]
