# Generated by Django 5.2.7 on 2025-11-16 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticketinfo_availability_alter_ticketinfo_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketinfo",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to hide this ticket type from the order form.",
            ),
        ),
        migrations.AlterField(
            model_name="ticketinfo",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
