# Generated by Django 5.2.7 on 2025-11-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticketinfo_is_active_alter_ticketinfo_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketinfo",
            options={"ordering": ["category"]},
        ),
        migrations.AlterField(
            model_name="ticketinfo",
            name="category",
            field=models.CharField(
                choices=[
                    ("Early Bird", "Early Bird"),
                    ("General Admission", "General Admission"),
                    ("VIP", "VIP"),
                ],
                max_length=50,
            ),
        ),
    ]
