# Generated by Django 5.2.7 on 2025-12-10 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_ticketinfo_options_alter_ticketinfo_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketinfo",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
